### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by nemoo** [kenshoo/metrics-play#25]
Hi!

I have just added metrics-play to my play scala app and it works great. Right now I am looking at com.kenshoo.play.metrics.MetricsFilter.requestTimer and it looks really helpfull.
However, I would like to have the very same information as provided by the general requestTimer, but for each route of my app individually.
How would I have to proceed? Is there maybe a sample play scala app where this has been done?

Thanks!

**Comment by liorhar** [comment]
That's not possible at the moment, the MetricsFilter will register all meters with the same name.
Need to make that class configurable.

**Comment by agapep** [comment]
I have my own implementation of MetricsFilter which could be helpful for you. 
See https://github.com/agapep/metrics-play/blob/master/src/main/scala/com/kenshoo/play/metrics/RoutesMetricsFilter.scala

(I perform only basic test with it. Personally I use more complex implementation with more app specyfic metrics)

**Comment by mosheeshel** [comment]
We're looking to implement this in the project
