### ISSUE TITLE
'max' value for Timer metric decreasing over time

### ISSUE THREAD

**Issue by giridhara** [kenshoo/metrics-play#26]
I am doing load testing, and using metrics-play for finding time taken by requests.

I did two load tests , one after another. But did not restart play application between load tests.
I see 'max' value for a timer metric getting decreased when i ran second load test.
'count' value for the same timer metric looks proper.

Is there any explanation for why 'max' value decreased ?

Thanks,
Giridhar.

**Comment by liorhar** [comment]
Yes, Timers use histograms with exponentially decaying reservoirs by default. 
see here - https://dropwizard.github.io/metrics/3.1.0/manual/core/
