### ISSUE TITLE
support for refreshing counters for metrics

### ISSUE THREAD

**Issue by giridhara** [kenshoo/metrics-play#27]
Hi,

Is it possible to provide support for refreshing metric values ( possibly via end point like /admin/metrics )
This would be helpful for refreshing metrics between two successive runs of load tests.

Thanks,
Giridhar.

**Comment by liorhar** [comment]
what do  you mean refreshing metric values? they're always up to date. do you mean reset?

**Comment by giridhara** [comment]
Sorry for wrong choice of word.
Yes, i meant 'reset'.

Thanks,
Giridhar.

**Comment by liorhar** [comment]
reset isn't supported by the metrics library itself, metrics-play is just a wrapper around it
https://github.com/dropwizard/metrics/pull/450
