### ISSUE TITLE
Use metrics with a Java project

### ISSUE THREAD

**Issue by SebT** [kenshoo/metrics-play#40]
Hi,

Is this compatible with a Java project? By reading your README it seems that only scala is supported and I can't get it working in java, sbt doesn't find the dependency.

**Comment by TigranTsat** [comment]
I used it for Java project and it worked (JSON api worked). As far as I understand there is no direct Java project in Play. It will be Java + scala.
Are you sure that you included dependency correctly and restarted play?

**Comment by liorhar** [comment]
please see if the new module fixes your issue.
