### ISSUE TITLE
How to extend MetricsController for custom Auth actions in Java?

### ISSUE THREAD

**Issue by TigranTsat** [kenshoo/metrics-play#41]
Hi, I am trying to extend MetricsController to include my own Authentication action, but without any success:

@SecureAdminAction
public class MyMetricsController extends MetricsController {
}
It fails with "The type MetricsController cannot be the superclass of MyMetricsController; a superclass must be a class"
Can you, please, give me some hints how it can be done? I am new to scala.
Thanks.

**Comment by liorhar** [comment]
right, that's cause MetricsController is a scala Object, once we'll migrate to new dependency injection it will be sorted out.

**Comment by gpgekko** [comment]
Has this been fixed? And if so, is there any documentation or pointers to how it should be done?
