### ISSUE TITLE
Please publish Scala 2.10 version of 2.4.0_0.3.0

### ISSUE THREAD

**Issue by toldervoll** [kenshoo/metrics-play#47]
Hi!
For versions prior to  2.4.0_0.3.0 both Scala 2.10 and Scala 2.11 builds were published to Sonatype. For  2.4.0_0.3.0, however, I can only find the Scala 2.11 build. Could you please publish "com.kenshoo" % "metrics-play_2.10" % "2.4.0_0.3.0"?

We are unfortunately stuck on Scala 2.10 for now - we use Apache Spark as a service (Google Dataproc), and Spark still use Scala 2.10 for their official binaries. We use Play 2.4 and metrics, and we would like to use your excellent metrics library. I've run "sbt +publishLocal" to test the 2.10 version, and it seems to work fine.

**Comment by liorhar** [comment]
will do, though note it's not officially supported by play either
https://www.playframework.com/documentation/2.4.x/Migration24

**Comment by toldervoll** [comment]
Great, thanks! Our code is Scala only and all our dependencies are Java 7-compatible (AFAIK) so I think Play 2.4 and Scala 2.10 should work for us. We'll switch to Scala 2.11 as soon as Spark binaries are available with 2.11 - my guess is Spark 1.6 in December. Until then there are probably more people in the same situation as us.

**Comment by liorhar** [comment]
just released 2.4.0_0.4.0 version with scala 2.10 support
