### ISSUE TITLE
Latest jar still contains old files

### ISSUE THREAD

**Issue by thisismana** [kenshoo/metrics-play#48]
I guess you forgot to clean your workspace before, but there are still old class files in the release jar, that aren't supposed to be there (like `MetricsPlugin.class`).

We had a `play.plugins` that was still referencing this and togehter with the new Guice-Stuff caused a "metric was already registered" exceptions.

Version: `metrics-play_2.11-2.4.0_0.4.0`

**Comment by liorhar** [comment]
sorry about that. released a clean version.
