### ISSUE TITLE
Play 2.6

### ISSUE THREAD

**Issue by lloydmeta** [kenshoo/metrics-play#57]
I'm not sure if this repo has been abandoned given the deafening silence on #50, but for completeness, I just want to mention that Play 2.6 has been released ~ 1 week ago.

**Comment by AvihayTsayeg** [comment]
Thx, @lloydmeta 
Was not abandoned, just small vacation :wink: .

@rannisim @yaelballa 
It is time to back here

**Comment by lloydmeta** [comment]
@AvihayTsayeg can you take a look at #59?

**Comment by AvihayTsayeg** [comment]
@lloydmeta , @jostick 
Looking at with @rannisim

**Comment by mosheeshel** [comment]
Upgraded to 2.6.2
https://github.com/kenshoo/metrics-play/pull/59

**Comment by mosheeshel** [comment]
Release to maven should follow soon
