### ISSUE TITLE
2.11.x support

### ISSUE THREAD

**Issue by lloydmeta** [kenshoo/metrics-play#65]
Hi,

Thanks for the great lib. Would it be possible to have a 2.11.x version of this library published?

From what I can tell, it should just be a matter of adding 2.11.11 to the crossScalaVersions settings key, since Play 2.6.x still supports 2.11.

Thanks,

Lloyd

**Comment by mosheeshel** [comment]
@lloydmeta hi sorry for the delay, @rannisim can you take a look? I don't see why not.

**Comment by lloydmeta** [comment]
@mosheeshel no worries. Since it looks like you're open to the idea, I've opened #67 implementing this.

**Comment by lloydmeta** [comment]
@AvihayTsayeg @mosheeshel thanks for merging. Do you know when you will be able to release the newly added 2.11 version ? I have a project that I'd like to use it in :)

**Comment by stewSquared** [comment]
Thank you for adding this!
I'll note that I found the cross-published artifacts in maven with version`2.6.6_0.6.2`
You might want add that to the README!
