### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by z687wang** [kenshoo/metrics-play#66]
Hi, After I added dependecy, I got following compiling errors:
An exception or error caused a run to abort: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: play.api.mvc.EssentialFilter.$init$(Lplay/api/mvc/EssentialFilter;)V
  at com.kenshoo.play.metrics.MetricsFilterImpl.<init>(MetricsFilter.scala:36)
  while locating com.kenshoo.play.metrics.MetricsFilterImpl
  at com.kenshoo.play.metrics.PlayModule.bindings(PlayModule.scala:10):
Binding(interface com.kenshoo.play.metrics.MetricsFilter to ConstructionTarget(class com.kenshoo.play.metrics.MetricsFilterImpl) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating com.kenshoo.play.metrics.MetricsFilter

BTW, my Play version: 2.6.2
          my Scala version: 2.12

Thanks,
Walt Wang

**Comment by mosheeshel** [comment]
@z687wang please check your versions again, as it seems that this is a known issue in play but in previous versions, which implies you are using the wrong one (at least in runtime)
https://stackoverflow.com/a/38316946/445581

**Comment by z687wang** [comment]
Thanks.
