### ISSUE TITLE
Disable metrics.PlayModule > throws 'No implementation' exception

### ISSUE THREAD

**Issue by pme123** [kenshoo/metrics-play#69]
I use version: `2.6.6_0.6.2` (also tried `2.6.2_0.6.1`)
If I disable the Module:
```
play.modules {
  disabled += "com.kenshoo.play.metrics.PlayModule"
}
```
I get the following exception:
```
com.google.inject.CreationException: Unable to create injector, see the following errors:
...
4) No implementation for com.kenshoo.play.metrics.Metrics was bound.
  while locating com.kenshoo.play.metrics.Metrics
    for the 1st parameter of com.kenshoo.play.metrics.MetricsController.<init>(MetricsController.scala:23)
  while locating com.kenshoo.play.metrics.MetricsController
    for the 7th parameter of router.Routes.<init>(Routes.scala:55)
  while locating router.Routes
```

**Comment by rannisim** [comment]
Hi @pme123 ,
I'm not quite sure with what you are trying to achieve here, it will help if you will provide more info.

Anyway, disabling the ```PlayModule``` while still setting a route to the MetricsController won't work unless you will provide an implementation of your own.
If for example you are trying to disable the metric in some env type, you can set ```metrics.enabled = false``` in the application configuration and this will replace the deafult ```Metrics trait``` implementation with a stubbed one ```DisabledMetrics``` which does nothing. Can be seen [here](https://github.com/kenshoo/metrics-play/blob/80cd0715794c2dfa7a7aa43a5bbb54b3a765bf4e/src/main/scala/com/kenshoo/play/metrics/PlayModule.scala#L8).
