### ISSUE TITLE
Unresolved dependency and incompatible version of play.api.mvc.

### ISSUE THREAD

**Issue by toniclecb** [kenshoo/metrics-play#71]
Hi,

I wrote the dependency below in build.sbt:
```
libraryDependencies ++= Seq(
  "com.kenshoo" %% "metrics-play" % "2.6.2_0.6.1"
)
```
and the system shows this log:
```
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.kenshoo#metrics-play_2.11;2.6.2_0.6.1: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: com.kenshoo#metrics-play_2.11;2.6.2_0.6.1: not found
```

Did I need a specific **resolvers** in build.sbt file?
My project is Java, will it work fine?

scalaVersion := "2.11.7"

**Comment by toniclecb** [comment]
I changed to 
`"com.kenshoo" %% "metrics-play" % "2.6.6_0.6.2"`
and it works now.

But now I have this problem:
```
[error] missing or invalid dependency detected while loading class file 'MetricsController.class'.
[error] Could not access type AbstractController in package play.api.mvc,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)

A full rebuild may help if 'MetricsController.class' was compiled against an incompatible version of play.api.mvc.]
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
        at scala.Option.map(Option.scala:145)
```

**Comment by tzachz** [comment]
What Play version are you using? Looks like you're using `2.6.2` with Scala `2.11.7` - for which indeed there seems to be no suitable artifact (see [here](https://mvnrepository.com/artifact/com.kenshoo/metrics-play) - `2.6.2_0.6.1` only has a Scala `2.12` artifact). I can look into that but please verify the required Play version.

**Comment by toniclecb** [comment]
Thanks.

I was able to run it with version `"com.kenshoo" %% "metrics-play" % "2.5.9_0.5.1"`

I am already seeing the log, but I need the logs for each request in Java, there is some page to see about it?

My project is in Java and it doesn't have Global, only Module and Filters.

**Comment by tzachz** [comment]
Glad the dependency issue worked out; 

> I need the logs for each request in Java

Not sure what you mean - can you clarify? Do you mean you want to instrument HTTP requests using the `MetricsFilter`? If so, I believe you can follow [this documentation](https://www.playframework.com/documentation/2.6.x/JavaHttpFilters#Using-filters) and inject an instance of `MetricsFilter` into your `Filters` class constructor.

Since this is unrelated to the issue at hand, mind if I close it?

**Comment by toniclecb** [comment]
The problem was solved.

Thank you
